### ISSUE TITLE
All content is brought in unpublished if content moderation enabled

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_legacy_migration#2]
Migrate process is not publlishing content when content moderation / workflow modules are enabled. Requires manual publication.

**Comment by andybroomfield** [comment]
If we can't solve this via migration with `moderation_state: moderation_state` then we managed to do this with BHCC migrated Drupal 7 content using the following.

````yaml
moderation_state:
    -
      plugin: static_map
      source: status
      default_value: draft
      map:
        '0': draft
        '1': published
````
